name: LifeNetScoreboard
version: '${project.version}'
main: me.ghostedvortex.lifenetscoreboard.LifeNetScoreboard
author: ghostedvortex
description: LifeNetwork plugin for the scoreboard.
api-version: '1.20'
load: STARTUP
